services:
  - type: worker
    name: telegram-gpt-bot
    runtime: python
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        value: PLACEHOLDER
      - key: OPENAI_API_KEY
        value: PLACEHOLDER
